#include <SDL2/SDL.h>
#include "sdl2_local.h"
#include <iostream>
#include "measure2.h"
#include <opencv2/opencv.hpp>
#include "config.h"

using namespace std::chrono;



struct SDL2_Window_State
{
    SDL_Window *window = nullptr;
    SDL_Renderer *renderer = nullptr;
    SDL_Texture *texture = nullptr;
    int tex_width = 0;
    int tex_height = 0;
};


// generated by claude
bool sdl2_multi_imshow(const std::string &window_name, const cv::Mat &image)
{
    static bool initialized = false;
    static std::unordered_map<std::string, SDL2_Window_State> windows;

    if (image.empty())
        return true;

    if (image.type() != CV_8UC3)
    {
        std::cerr << "sdl2_imshow expects CV_8UC3\n";
        return false;
    }

    if (!initialized)
    {
        if (SDL_Init(SDL_INIT_VIDEO) != 0)
        {
            std::cerr << "SDL_Init failed: " << SDL_GetError() << std::endl;
            return false;
        }
        initialized = true;
    }

    SDL2_Window_State &state = windows[window_name];

    if (!state.window)
    {
        state.window = SDL_CreateWindow(
            window_name.c_str(),
            SDL_WINDOWPOS_CENTERED,
            SDL_WINDOWPOS_CENTERED,
            image.cols,
            image.rows,
            SDL_WINDOW_SHOWN | SDL_WINDOW_RESIZABLE);

        if (!state.window)
        {
            std::cerr << "SDL_CreateWindow failed: " << SDL_GetError() << std::endl;
            return false;
        }

        state.renderer = SDL_CreateRenderer(state.window, -1, SDL_RENDERER_ACCELERATED);

        if (!state.renderer)
        {
            std::cerr << "SDL_CreateRenderer failed: " << SDL_GetError() << std::endl;
            return false;
        }
    }

    if (!state.texture ||
        image.cols != state.tex_width ||
        image.rows != state.tex_height)
    {
        if (state.texture)
            SDL_DestroyTexture(state.texture);

        state.texture = SDL_CreateTexture(
            state.renderer,
            SDL_PIXELFORMAT_BGR24,
            SDL_TEXTUREACCESS_STREAMING,
            image.cols,
            image.rows);

        if (!state.texture)
        {
            std::cerr << "SDL_CreateTexture failed: " << SDL_GetError() << std::endl;
            return false;
        }

        state.tex_width = image.cols;
        state.tex_height = image.rows;
    }

    // LockTexture fast path — avoids SDL_UpdateTexture's extra copy
    void *pixels = nullptr;
    int pitch = 0;
    if (SDL_LockTexture(state.texture, nullptr, &pixels, &pitch) != 0)
    {
        std::cerr << "SDL_LockTexture failed: " << SDL_GetError() << std::endl;
        return false;
    }

    const int row_bytes = image.cols * 3;
    if (pitch == row_bytes && image.isContinuous())
    {
        memcpy(pixels, image.data, (size_t)row_bytes * image.rows);
    }
    else
    {
        const uint8_t *src = image.data;
        uint8_t *dst = static_cast<uint8_t *>(pixels);
        for (int y = 0; y < image.rows; y++, src += image.step, dst += pitch)
            memcpy(dst, src, row_bytes);
    }

    SDL_UnlockTexture(state.texture);

    SDL_RenderClear(state.renderer);
    SDL_RenderCopy(state.renderer, state.texture, nullptr, nullptr);
    SDL_RenderPresent(state.renderer);

    // Drain ALL pending events, routing quit/escape globally
    SDL_Event event;
    while (SDL_PollEvent(&event))
    {
        if (event.type == SDL_QUIT)
            return false;

        if (event.type == SDL_WINDOWEVENT &&
            event.window.event == SDL_WINDOWEVENT_CLOSE)
            return false;

        if (event.type == SDL_KEYDOWN &&
            event.key.keysym.sym == SDLK_ESCAPE)
            return false;
    }

    return true;
}



void Update_And_Show_Main_Displays_sdl2(std::array<cv::Mat, 4> &Main_Display)
{
    static bool first_time = true;

    if (!Main_Display[0].empty())
        sdl2_multi_imshow("sdl 0 Video", Main_Display[0]);

    if (!Main_Display[1].empty())
        sdl2_multi_imshow("sdl 1 Video", Main_Display[1]);

    if (!Main_Display[2].empty())
        sdl2_multi_imshow("sdl 2 Video", Main_Display[2]);

    if (!Main_Display[3].empty())
        sdl2_multi_imshow("sdl 3 Video", Main_Display[3]);
}



// Change return type from void to bool
bool Update_And_Show_Main_Displays_sdl2_2(std::array<cv::Mat, 4> &Main_Display)
{
    if (!Main_Display[2].empty())
        if (!sdl2_multi_imshow("sdl 2 Video", Main_Display[2]))
            return false;

    if (!Main_Display[3].empty())
        if (!sdl2_multi_imshow("sdl 3 Video", Main_Display[3]))
            return false;

    return true;
}

